/**
 * Consultas SOMENTE LEITURA no GlobalSys (Microled).
 *
 * Nunca emitir INSERT, UPDATE, DELETE ou ALTER contra esse banco.
 *
 * Fonte: PROC_EDI_PROCESSA_* (Luciana) + INFORMATION_SCHEMA.
 *
 * Textos operacionais vêm dos JOINs de TB_BL (IDs). Quando o EDI não
 * resolveu o cadastro (ID = 0), o fallback são as tabelas TB_MANIFESTO_*.
 */

const SQL_RESOLVE_ID_BL = `(
  SELECT TOP 1 innerBl.ID_BL
  FROM TB_BL innerBl
  WHERE innerBl.NR_BL = @numeroBL
    AND innerBl.DT_CANCELAMENTO IS NULL
  ORDER BY innerBl.ID_BL DESC
)`;

export const SQL_FIND_TB_BL = `
SELECT TOP 1
  bl.ID_BL,
  bl.NR_BL,
  bl.GRAU,
  COALESCE(
    NULLIF(LTRIM(RTRIM(bl.REFERENCIA_EDI)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.REFERENCE_NUMBER)), '')
  ) AS REFERENCIA_EDI,
  COALESCE(
    NULLIF(LTRIM(RTRIM(bl.NR_VIAGEM)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.VOYAGE)), '')
  ) AS NR_VIAGEM,
  COALESCE(bl.QT_MERCADORIA, manHouse.PACKING_QUANTITY, manMaster.PACKING_QUANTITY) AS QT_MERCADORIA,
  COALESCE(
    bl.VL_PESO_BRUTO,
    manHouse.GROSS_WEIGHT,
    TRY_CONVERT(decimal(18, 3), manMaster.GROSS_WEIGHT)
  ) AS VL_PESO_BRUTO,
  COALESCE(
    bl.VL_M3,
    manHouse.VOLUME_MEASURE,
    TRY_CONVERT(decimal(18, 3), manMaster.VOLUME_MEASURE)
  ) AS VL_M3,
  COALESCE(
    NULLIF(LTRIM(RTRIM(navio.NM_NAVIO)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.VESSEL_NAME)), '')
  ) AS NM_NAVIO,
  COALESCE(
    NULLIF(LTRIM(RTRIM(pagamento.NM_TIPO_PAGAMENTO)), ''),
    CASE UPPER(LTRIM(RTRIM(pagamento.CD_TIPO_PAGAMENTO)))
      WHEN 'P' THEN 'PREPAID'
      WHEN 'C' THEN 'COLLECT'
      ELSE NULLIF(LTRIM(RTRIM(pagamento.CD_TIPO_PAGAMENTO)), '')
    END,
    CASE UPPER(LTRIM(RTRIM(COALESCE(manHouse.FREIGHT_TERM, manMaster.FREIGHT_TERM))))
      WHEN 'P' THEN 'PREPAID'
      WHEN 'C' THEN 'COLLECT'
      ELSE NULLIF(LTRIM(RTRIM(COALESCE(manHouse.FREIGHT_TERM, manMaster.FREIGHT_TERM))), '')
    END
  ) AS NM_TIPO_PAGAMENTO,
  COALESCE(
    NULLIF(LTRIM(RTRIM(transportador.NM_RAZAO)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.CARRIER_NAME)), '')
  ) AS NM_TRANSPORTADOR,
  NULLIF(LTRIM(RTRIM(manMaster.CARRIER_SCAC_CODE)), '') AS CD_SCAC,
  COALESCE(
    NULLIF(LTRIM(RTRIM(shipper.NM_RAZAO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.SHIPPER_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.SHIPPER_NAME)), '')
  ) AS NM_SHIPPER,
  COALESCE(
    NULLIF(LTRIM(RTRIM(cnee.NM_RAZAO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.CONSIGNEE_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.CONSIGNEE_NAME)), '')
  ) AS NM_CONSIGNEE,
  COALESCE(
    NULLIF(LTRIM(RTRIM(notify.NM_RAZAO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.NOTIFY_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.NOTIFY_NAME)), '')
  ) AS NM_NOTIFY,
  COALESCE(
    NULLIF(LTRIM(RTRIM(origem.CD_SIGLA_MARINHA_MERCANTE)), ''),
    NULLIF(LTRIM(RTRIM(bl.SIGLA_ORIGEM)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.LOADING_PORT_CODE)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.LOADING_PORT_CODE)), '')
  ) AS CD_PORTO_ORIGEM,
  COALESCE(
    NULLIF(LTRIM(RTRIM(origem.NM_PORTO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.LOADING_PORT_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.LOADING_PORT_NAME)), '')
  ) AS NM_PORTO_ORIGEM,
  COALESCE(
    NULLIF(LTRIM(RTRIM(destino.CD_SIGLA_MARINHA_MERCANTE)), ''),
    NULLIF(LTRIM(RTRIM(bl.SIGLA_DESTINO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.DISCHARGE_PORT_CODE)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.DISCHARGE_PORT_CODE)), '')
  ) AS CD_PORTO_DESTINO,
  COALESCE(
    NULLIF(LTRIM(RTRIM(destino.NM_PORTO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.DISCHARGE_PORT_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.DISCHARGE_PORT_NAME)), '')
  ) AS NM_PORTO_DESTINO,
  COALESCE(
    NULLIF(LTRIM(RTRIM(cidade.NM_CIDADE)), ''),
    NULLIF(LTRIM(RTRIM(destino.NM_PORTO)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.DELIVERY_PORT_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.DELIVERY_PORT_NAME)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.FINAL_DESTINATION_PORT_NAME)), '')
  ) AS NM_DESTINO_FINAL,
  COALESCE(
    NULLIF(LTRIM(RTRIM(cntr.NR_CNTR)), ''),
    NULLIF(LTRIM(RTRIM(manCntr.CONTAINER_NUMBER)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.CONTAINER_NUMBER)), '')
  ) AS NR_CNTR,
  COALESCE(
    NULLIF(LTRIM(RTRIM(cntr.NR_LACRE)), ''),
    NULLIF(LTRIM(RTRIM(manCntr.CONTAINER_SEAL_NO1)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.CONTAINER_SEAL)), '')
  ) AS NR_LACRE,
  COALESCE(
    NULLIF(LTRIM(RTRIM(tipoCntr.NM_TIPO_CONTAINER)), ''),
    NULLIF(LTRIM(RTRIM(manCntr.CONTAINER_TYPE)), ''),
    NULLIF(LTRIM(RTRIM(manMaster.CONTAINER_TYPE)), '')
  ) AS NM_TIPO_CONTAINER,
  COALESCE(
    NULLIF(LTRIM(RTRIM(unidade.NM_MERCADORIA)), ''),
    NULLIF(LTRIM(RTRIM(manCntr.CONTAINER_UNIT_CODE)), '')
  ) AS NM_UNIDADE_EMBALAGEM,
  COALESCE(
    NULLIF(LTRIM(RTRIM(carga.DS_MERCADORIA)), ''),
    NULLIF(LTRIM(RTRIM(manHouse.ITEM_NAME)), ''),
    NULLIF(LTRIM(RTRIM(bl.DS_MERCADORIA_GERAL)), ''),
    NULLIF(LTRIM(RTRIM(bl.NM_RESUMO_MERCADORIA)), '')
  ) AS DS_MERCADORIA,
  COALESCE(
    CONVERT(varchar(10), bl.DT_EMISSAO_BL, 23),
    CONVERT(varchar(10), bl.DT_EMISSAO_CONHECIMENTO, 23),
    NULLIF(LTRIM(RTRIM(manHouse.ISSUE_DATE)), '')
  ) AS DT_EMISSAO_BL
FROM TB_BL bl
LEFT JOIN TB_NAVIO navio
  ON navio.ID_NAVIO = bl.ID_NAVIO
LEFT JOIN TB_TIPO_PAGAMENTO pagamento
  ON pagamento.ID_TIPO_PAGAMENTO = bl.ID_TIPO_PAGAMENTO
LEFT JOIN TB_PARCEIRO transportador
  ON transportador.ID_PARCEIRO = bl.ID_PARCEIRO_TRANSPORTADOR
LEFT JOIN TB_PARCEIRO shipper
  ON shipper.ID_PARCEIRO = bl.ID_PARCEIRO_SHIPPER
LEFT JOIN TB_PARCEIRO cnee
  ON cnee.ID_PARCEIRO = bl.ID_PARCEIRO_CNEE
LEFT JOIN TB_PARCEIRO notify
  ON notify.ID_PARCEIRO = bl.ID_PARCEIRO_NOTIFY
LEFT JOIN TB_PORTO origem
  ON origem.ID_PORTO = bl.ID_PORTO_ORIGEM
LEFT JOIN TB_PORTO destino
  ON destino.ID_PORTO = bl.ID_PORTO_DESTINO
LEFT JOIN TB_CIDADE cidade
  ON cidade.ID_CIDADE = bl.ID_FINAL_DESTINATION
LEFT JOIN TB_MERCADORIA unidade
  ON unidade.ID_MERCADORIA = bl.ID_MERCADORIA
LEFT JOIN TB_MANIFESTO_BL manMaster
  ON manMaster.ID = bl.ID_MANIFESTO_BL
 AND ISNULL(bl.ID_MANIFESTO_BL, 0) > 0
LEFT JOIN TB_MANIFESTO_HOUSE_BL manHouse
  ON manHouse.ID = bl.ID_MANIFESTO_HOUSE_BL
 AND ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) > 0
OUTER APPLY (
  SELECT TOP 1
    cntrInner.NR_CNTR,
    cntrInner.NR_LACRE,
    cntrInner.ID_TIPO_CNTR
  FROM TB_AMR_CNTR_BL amr
  INNER JOIN TB_CNTR_BL cntrInner
    ON cntrInner.ID_CNTR_BL = amr.ID_CNTR_BL
  WHERE amr.ID_BL = bl.ID_BL
  ORDER BY cntrInner.ID_CNTR_BL
) cntr
LEFT JOIN TB_TIPO_CONTAINER tipoCntr
  ON tipoCntr.ID_TIPO_CONTAINER = cntr.ID_TIPO_CNTR
OUTER APPLY (
  SELECT TOP 1
    manCntrInner.CONTAINER_NUMBER,
    manCntrInner.CONTAINER_SEAL_NO1,
    manCntrInner.CONTAINER_TYPE,
    manCntrInner.CONTAINER_UNIT_CODE
  FROM TB_MANIFESTO_CNTR_BL manCntrInner
  WHERE (
      ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) > 0
      AND manCntrInner.ID_HOUSE = bl.ID_MANIFESTO_HOUSE_BL
    )
    OR (
      ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) = 0
      AND ISNULL(bl.ID_MANIFESTO_BL, 0) > 0
      AND manCntrInner.ID_MASTER = bl.ID_MANIFESTO_BL
    )
  ORDER BY manCntrInner.ID
) manCntr
OUTER APPLY (
  SELECT TOP 1 cargaInner.DS_MERCADORIA
  FROM TB_CARGA_BL cargaInner
  WHERE cargaInner.ID_BL = bl.ID_BL
  ORDER BY cargaInner.NR_ITEM_CARGA, cargaInner.ID_CARGA_BL
) carga
WHERE bl.ID_BL = ${SQL_RESOLVE_ID_BL}
`;

export const SQL_FIND_CARGA = `
SELECT
  COALESCE(c.MARCA, man.BRAND) AS MARCA,
  COALESCE(c.CONTRAMARCA, man.COUNTER_MARK) AS CONTRAMARCA,
  COALESCE(tipo.NM_TIPO_CARGA, man.CARGO_TYPE) AS NM_TIPO_CARGA,
  COALESCE(c.CLASSE_PERIGO, man.HAZARD_CLASS) AS CLASSE_PERIGO,
  COALESCE(c.COD_CARGA_PERIGOSA, man.UN_NUMBER) AS COD_CARGA_PERIGOSA,
  COALESCE(emb.NM_MERCADORIA, man.PACKAGING) AS NM_EMBALAGEM,
  COALESCE(c.DS_MERCADORIA, manHouse.ITEM_NAME) AS DS_MERCADORIA
FROM TB_CARGA_BL c
LEFT JOIN TB_TIPO_CARGA tipo
  ON tipo.ID_TIPO_CARGA = c.ID_TIPO_CARGA
LEFT JOIN TB_MERCADORIA emb
  ON emb.ID_MERCADORIA = c.ID_EMBALAGEM
LEFT JOIN TB_MANIFESTO_HOUSE_CARGA man
  ON man.ID = c.ID_MANIFESTO_HOUSE_CARGA
 AND ISNULL(c.ID_MANIFESTO_HOUSE_CARGA, 0) > 0
LEFT JOIN TB_BL bl
  ON bl.ID_BL = c.ID_BL
LEFT JOIN TB_MANIFESTO_HOUSE_BL manHouse
  ON manHouse.ID = bl.ID_MANIFESTO_HOUSE_BL
 AND ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) > 0
WHERE c.ID_BL = ${SQL_RESOLVE_ID_BL}

UNION ALL

SELECT
  man.BRAND,
  man.COUNTER_MARK,
  man.CARGO_TYPE,
  man.HAZARD_CLASS,
  man.UN_NUMBER,
  man.PACKAGING,
  manHouse.ITEM_NAME
FROM TB_MANIFESTO_HOUSE_CARGA man
INNER JOIN TB_BL bl
  ON bl.ID_MANIFESTO_HOUSE_BL = man.ID_HOUSE
 AND ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) > 0
LEFT JOIN TB_MANIFESTO_HOUSE_BL manHouse
  ON manHouse.ID = man.ID_HOUSE
WHERE bl.ID_BL = ${SQL_RESOLVE_ID_BL}
  AND NOT EXISTS (
    SELECT 1 FROM TB_CARGA_BL c WHERE c.ID_BL = bl.ID_BL
  )
`;

export const SQL_FIND_NCM = `
SELECT DISTINCT CD_NCM
FROM (
  SELECT ncm.CD_NCM AS CD_NCM
  FROM TB_BL_NCM blncm
  INNER JOIN TB_NCM ncm
    ON ncm.ID_NCM = blncm.ID_NCM
  WHERE blncm.ID_BL = ${SQL_RESOLVE_ID_BL}

  UNION ALL

  SELECT man.NCM_CODE
  FROM TB_MANIFESTO_HOUSE_NCM man
  INNER JOIN TB_BL bl
    ON bl.ID_MANIFESTO_HOUSE_BL = man.ID_HOUSE
   AND ISNULL(bl.ID_MANIFESTO_HOUSE_BL, 0) > 0
  WHERE bl.ID_BL = ${SQL_RESOLVE_ID_BL}
) ncmSource
WHERE CD_NCM IS NOT NULL
  AND LTRIM(RTRIM(CD_NCM)) <> ''
`;

/**
 * Consulta Master para a tela de Divergências (BL Final × GlobalSys).
 * Uma linha por container (DISTINCT). Não há SCAC operacional em TB_BL.
 *
 * FreightTerm usa NM_TIPO_PAGAMENTO (PREPAID/COLLECT). CD_TIPO_PAGAMENTO é P/C
 * e não bate com o BL Final se for comparado cru.
 */
export const SQL_FIND_MASTER_DIVERGENCIA = `
SELECT DISTINCT
    BL.NR_BL AS MasterNumber,
    NAVIO.NM_NAVIO AS VesselName,
    BL.NR_VIAGEM AS Voyage,
    -- Não foi identificado campo operacional para SCAC no script
    NULL AS CarrierSCACCode,
    CARRIER.NM_RAZAO AS CarrierName,
    COALESCE(
        NULLIF(LTRIM(RTRIM(PAGAMENTO.NM_TIPO_PAGAMENTO)), ''),
        CASE UPPER(LTRIM(RTRIM(PAGAMENTO.CD_TIPO_PAGAMENTO)))
            WHEN 'P' THEN 'PREPAID'
            WHEN 'C' THEN 'COLLECT'
            ELSE NULLIF(LTRIM(RTRIM(PAGAMENTO.CD_TIPO_PAGAMENTO)), '')
        END
    ) AS FreightTerm,
    CNTR.NR_CNTR AS ContainerNumber,
    CNTR.NR_LACRE AS ContainerSealNo1,
    TIPO_CNTR.NM_TIPO_CONTAINER AS ContainerType
FROM TB_BL BL
LEFT JOIN TB_NAVIO NAVIO
    ON NAVIO.ID_NAVIO = BL.ID_NAVIO
LEFT JOIN TB_PARCEIRO CARRIER
    ON CARRIER.ID_PARCEIRO = BL.ID_PARCEIRO_TRANSPORTADOR
LEFT JOIN TB_TIPO_PAGAMENTO PAGAMENTO
    ON PAGAMENTO.ID_TIPO_PAGAMENTO = BL.ID_TIPO_PAGAMENTO
LEFT JOIN TB_AMR_CNTR_BL AMR
    ON AMR.ID_BL = BL.ID_BL
LEFT JOIN TB_CNTR_BL CNTR
    ON CNTR.ID_CNTR_BL = AMR.ID_CNTR_BL
LEFT JOIN TB_TIPO_CONTAINER TIPO_CNTR
    ON TIPO_CNTR.ID_TIPO_CONTAINER = CNTR.ID_TIPO_CNTR
WHERE BL.NR_BL = @MasterNumber
  AND BL.DT_CANCELAMENTO IS NULL
`;

/**
 * Consulta House para a tela de Divergências (BL Final × GlobalSys).
 * Uma linha por item de TB_CARGA_BL. NCM agregado via STRING_AGG.
 *
 * DeliveryPortName / IssueDate / ItemName: o EDI muitas vezes não grava o
 * manifesto (ID_MANIFESTO_HOUSE_BL nulo) nem a carga descritiva. Nesses casos
 * o valor operacional está em TB_BL / TB_PORTO / TB_CIDADE.
 */
export const SQL_FIND_HOUSE_DIVERGENCIA = `
SELECT
    BL.NR_BL AS HouseNumber,
    SHIPPER.NM_RAZAO AS ShipperName,
    CONSIGNEE.NM_RAZAO AS ConsigneeName,
    NOTIFY.NM_RAZAO AS NotifyName,
    COALESCE(
        NULLIF(LTRIM(RTRIM(MH.DELIVERY_PORT_NAME)), ''),
        NULLIF(LTRIM(RTRIM(CIDADE.NM_CIDADE)), ''),
        NULLIF(LTRIM(RTRIM(DESTINO.NM_PORTO)), '')
    ) AS DeliveryPortName,
    BL.QT_MERCADORIA AS PackingQuantity,
    BL.VL_PESO_BRUTO AS GrossWeight,
    BL.VL_M3 AS VolumeMeasure,
    COALESCE(
        NULLIF(LTRIM(RTRIM(MH.ISSUE_DATE)), ''),
        CONVERT(varchar(10), BL.DT_EMISSAO_BL, 23),
        CONVERT(varchar(10), BL.DT_EMISSAO_CONHECIMENTO, 23)
    ) AS IssueDate,
    COALESCE(
        NULLIF(LTRIM(RTRIM(CARGA.DS_MERCADORIA)), ''),
        NULLIF(LTRIM(RTRIM(BL.DS_MERCADORIA_GERAL)), ''),
        NULLIF(LTRIM(RTRIM(BL.NM_RESUMO_MERCADORIA)), '')
    ) AS ItemName,
    NCM.NcmCode,
    CARGA.MARCA AS Brand,
    CARGA.CONTRAMARCA AS ConterMark,
    TIPO_CARGA.NM_TIPO_CARGA AS CargoType,
    CARGA.CLASSE_PERIGO AS HazardClass,
    CARGA.COD_CARGA_PERIGOSA AS UNNumber,
    MERCADORIA.NM_MERCADORIA AS Packaging
FROM TB_BL BL
LEFT JOIN TB_PARCEIRO SHIPPER
    ON SHIPPER.ID_PARCEIRO = BL.ID_PARCEIRO_SHIPPER
LEFT JOIN TB_PARCEIRO CONSIGNEE
    ON CONSIGNEE.ID_PARCEIRO = BL.ID_PARCEIRO_CNEE
LEFT JOIN TB_PARCEIRO NOTIFY
    ON NOTIFY.ID_PARCEIRO = BL.ID_PARCEIRO_NOTIFY
LEFT JOIN TB_PORTO DESTINO
    ON DESTINO.ID_PORTO = BL.ID_PORTO_DESTINO
LEFT JOIN TB_CIDADE CIDADE
    ON CIDADE.ID_CIDADE = BL.ID_FINAL_DESTINATION
LEFT JOIN TB_MANIFESTO_HOUSE_BL MH
    ON MH.ID = BL.ID_MANIFESTO_HOUSE_BL
   AND ISNULL(BL.ID_MANIFESTO_HOUSE_BL, 0) > 0
LEFT JOIN TB_CARGA_BL CARGA
    ON CARGA.ID_BL = BL.ID_BL
LEFT JOIN TB_TIPO_CARGA TIPO_CARGA
    ON TIPO_CARGA.ID_TIPO_CARGA = CARGA.ID_TIPO_CARGA
LEFT JOIN TB_MERCADORIA MERCADORIA
    ON MERCADORIA.ID_MERCADORIA = CARGA.ID_EMBALAGEM
OUTER APPLY
(
    SELECT
        STRING_AGG(X.CD_NCM, ',') AS NcmCode
    FROM
    (
        SELECT DISTINCT
            N.CD_NCM
        FROM TB_BL_NCM BN
        INNER JOIN TB_NCM N
            ON N.ID_NCM = BN.ID_NCM
        WHERE BN.ID_BL = BL.ID_BL
    ) X
) NCM
WHERE BL.NR_BL = @HouseNumber
  AND BL.DT_CANCELAMENTO IS NULL
`;
